---
ID: "a2e902bd-88ed-431b-a744-e5eb887caa5b"
Parent: "676179e1-3f48-4161-818b-66744b2d48f0"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Playground/int/Presentation/Rendering Variants/Link List/Default
DB: master
BranchID: "60ac3def-7cda-406b-8f40-4e4f0073e4c2"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133408Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
