---
ID: "c2916685-f3ae-4a70-a663-6dfe1f0233cd"
Parent: "eafe8e17-27e9-4dbe-bc08-a9fe4fb3b382"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Blog/blog/Presentation/Rendering Variants/Link List/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{C5678F86-D23D-41CA-B236-A1989FCFDAC7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171214T210921Z
