---
ID: "e362f4d4-3597-4747-bbff-3498aa5902c3"
Parent: "a3316395-89a7-4002-b9c1-2cf38297dd5a"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Playground/int/Presentation/Rendering Variants/Page List/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133356Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
