---
ID: "263814a0-7887-4238-bcff-3f705e3ffab4"
Parent: "f9378ed2-a3a1-4b47-95bf-d0da1561d165"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Playground/int/Presentation/Rendering Variants/Field Editor/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170213T152318Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
