---
ID: "e545790b-2d24-4b66-9545-5c94baa60da2"
Parent: "891199b1-4406-4f0e-9d91-bac72ddc550f"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Playground/pl/Presentation/Rendering Variants/Link/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170920T143525Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
