---
ID: "96b41905-f76e-44f0-a840-9ddaf6fd9ba3"
Parent: "867b0c45-dc9f-429a-bd4a-9ad25cbf8bdb"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Blog/blog/Presentation/Rendering Variants/Archive/Default
DB: master
SharedFields:
- ID: "e1d5adba-8348-4127-9bb6-455936653839"
  Hint: CssClass
  Value: "navigation-title"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{22ABAE07-60A6-4F59-847C-2BBD32A838AF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171214T210919Z
