---
ID: "11781cc0-cb21-4706-8a50-4eb2cf611db7"
Parent: "ba70385e-fbce-4e4c-8da9-1d455afa97a9"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Playground/int/Presentation/Rendering Variants/Breadcrumb/Default
DB: master
BranchID: "de3cdf1f-5d97-4c56-b213-94c2754261c6"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133407Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
