---
ID: "128ac368-4d2f-4f71-8b5c-0f1348efce46"
Parent: "9cd3cfbe-cc14-4dc2-8e54-d72f434940a6"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Playground/int/Presentation/Rendering Variants/Archive/Default
DB: master
BranchID: "de3cdf1f-5d97-4c56-b213-94c2754261c6"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133406Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
