---
ID: "e964a319-4a20-4f4b-9b7b-1bb95e333fa9"
Parent: "0b197821-1934-4e67-b456-4fbdffe209d5"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Playground/int/Presentation/Rendering Variants/POI/Default
DB: master
BranchID: "0f31020c-79af-47c9-b8e6-c98720ae8a13"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133344Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\Admin
