---
ID: "310e70ea-cc0d-4dd1-8f7f-b4c52cbf8cd2"
Parent: "e2e603d2-4a73-4be8-bb3e-1c0fc6f3379a"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Blog/blog/Presentation/Rendering Variants/POI/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{09180CD8-3CA2-4A92-B3B5-F4F057BA465C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171214T210857Z
