---
ID: "b29e3b89-eb19-4251-b5ce-cde40d9c5761"
Parent: "efa62406-cfd7-43c6-b702-3f53dfb1cee3"
Template: "efa62406-cfd7-43c6-b702-3f53dfb1cee3"
Path: /sitecore/templates/Project/SXA Reference/Blog/Blog/Blog Post/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171214T212747Z
    - ID: "fbcbcae4-6360-48e4-addb-defd4a16a5e2"
      Hint: Published
      Value: $now
