---
ID: "72a5dd14-995d-4e06-9e7f-bc00cc1a7957"
Parent: "3bb0640e-4de1-4bcc-9ce0-82c444dbd980"
Template: "efafbbf5-01a0-46d3-9f7b-e71763e7f221"
Path: /sitecore/content/SXA Reference/Blog/blog/Settings/Social Media Groups/Default
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{E35BE623-2154-4300-A80E-F054B26B76C5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171214T211000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
