---
ID: "4688bca4-93c9-42ef-bd4f-779fd6a039b6"
Parent: "0662e73b-c1eb-4ef0-a7d5-b43763f3a95c"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/SXA Reference/Playground/int/Presentation/Rendering Variants/Search Box/Default
DB: master
BranchID: "0d360bbd-4fae-4863-88b9-ae5be82be6f0"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133412Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\Admin
