---
ID: "bf796a76-d9cf-40d9-aaeb-cf00b623cab1"
Parent: "8e7a5044-10b3-4770-b892-bc8e20fed5a0"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/SXA Reference/Blog/blog/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180405T191421Z
