---
ID: "41ec5809-a752-4fd0-810f-a574dc0fc406"
Parent: "f0b39779-b2a8-4c60-9526-ba062ad83270"
Template: "efafbbf5-01a0-46d3-9f7b-e71763e7f221"
Path: /sitecore/content/SXA Reference/Playground/int/Settings/Social Media Groups/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133359Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
